### ISSUE TITLE
Missing configuration and template

### ISSUE THREAD

**Issue by msollmann** [Hauer-Heinrich/hh_accordion#2]
0.3.3

FE: The headline of the content element is not visible because of the missing setting tt_content.hhaccordion_hh_accordion.settings.defaultHeaderType (e.g. "= 2")

BE: The page module shows the error "Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file (Standard/Index.html). No paths configured.". Missing index-template?

**Comment by Teisi** [comment]
> BE: The page module shows the error "Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file (Standard/Index.html). No paths configured.". Missing index-template?

Have you included the PageTs ? :)

**Comment by msollmann** [comment]
O no... I had not. Thanks!
