### ISSUE TITLE
Feature: Open Accordion Tab by default

### ISSUE THREAD

**Issue by webdev2027** [Hauer-Heinrich/hh_accordion#3]
Great extension.
Maybe a good feature to open some tabs or accordion content by default.
See FlexForms f.e.

![Bildschirmfoto 2023-01-30 um 12 38 06](https://user-images.githubusercontent.com/5501876/215466811-98c1ddcb-bc55-403c-9376-a4bf00b8a296.png)

I've switched from my own Flux-Accordion to your extension, because I don' want to use Flux anymore.
Thanks.

**Comment by Teisi** [comment]
Info: Will be processed, could still take a par days
