### ISSUE TITLE
Why no TYPO3 9 Support

### ISSUE THREAD

**Issue by typo3max** [Hauer-Heinrich/hh_accordion#4]
WHY???????? PLEASE !!!!!

**Comment by Teisi** [comment]
Doesen't work version 2.0 https://github.com/Hauer-Heinrich/hh_accordion/tree/0.2.0 not for you?

**Comment by typo3max** [comment]
Oops, an error occurred!
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\ImageViewHelper: loading. Valid arguments are: additionalAttributes, data, class, dir, id, lang, style, title, accesskey, tabindex, onclick, alt, ismap, longdesc, usemap, src, treatIdAsReference, image, crop, cropVariant, width, height, minWidth, minHeight, maxWidth, maxHeight, absolute

**Comment by Teisi** [comment]
oh you are right the "loading" attribute exists only since TYPO3 10 - should be fixed with 0.2.1

**Comment by typo3max** [comment]
Thank You still waiting for 0.2.1

**Comment by typo3max** [comment]
Please report when you are finish with 2.0.1

**Comment by Teisi** [comment]
@typo3max have you additional error with this version 0.2.1?
Info: unfortunately the TER does not update this version - so you have to download it manually

**Comment by typo3max** [comment]
when i would find the link to download?!

**Comment by Teisi** [comment]
https://packagist.org/packages/hauerheinrich/hh-accordion#0.2.1
https://github.com/Hauer-Heinrich/hh_accordion/tree/TYPO3-9
https://github.com/Hauer-Heinrich/hh_accordion/tree/0.2.1

**Comment by typo3max** [comment]
I hope you get the extension published soon! I want send you some bucks end of the month, sry actually i have no cash too. But i want send you some soon!

**Comment by typo3max** [comment]
Ich möchte nicht frech werden, aber wann ist die Version 0.2.1 Accordions fertig? Bist du am Schlafen?

**Comment by Teisi** [comment]
> oh you are right the "loading" attribute exists only since TYPO3 10 - should be fixed with 0.2.1 : https://github.com/Hauer-Heinrich/hh_accordion/tree/TYPO3-9



> @typo3max have you additional error with this version 0.2.1? Info: unfortunately the TER does not update this version - so you have to download it manually

**Comment by typo3max** [comment]
Can you make a package to download, thank you!

**Comment by typo3max** [comment]
Oops, an error occurred!
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\ImageViewHelper: loading. Valid arguments are: additionalAttributes, data, class, dir, id, lang, style, title, accesskey, tabindex, onclick, alt, ismap, longdesc, usemap, src, treatIdAsReference, image, crop, cropVariant, width, height, minWidth, minHeight, maxWidth, maxHeight, absolute

**Comment by typo3max** [comment]
any answer? the version 0.2.1 dont work, same error!

**Comment by Teisi** [comment]
ah yes sorry - new version:
https://github.com/Hauer-Heinrich/hh_accordion/tree/0.2.2
